POST http://localhost:8083/painting
Content-Type: application/x-www-form-urlencoded

tags=house,lilac,by jean,mountain,construct,social,mankind,glass,Happiness,emotional,Beast,by Paul Cézanne,neon,sharp,crayon,cyberpunk,morose,giraffe,hypersurrealism,alchemy,cyborg&seed=2527636487&width=640&height=960&upscale=4&steps=50&version=v1.2