<template>
  <section class="content">
    <div class="has-text-centered">
      <span>subscribe to artchitect-10-min channel in telegram: <a href="https://t.me/artchitect_10min" target="_blank">https://t.me/artchitect_10min</a></span>
    </div>
    <hr/>
    <h1><img src="/icon64.png"/> Artchitect</h1>
    <p>
      <b>Artchitect</b> is the name of God, the Architect and Creator of the Universe.<br/>
      <a href="https://artchitect.space"><b>Artchitect</b>.space</a> is a <b>virtual temple of God</b> on the Internet,
      using artificial intelligence created by God and Humanity.
    </p>
    <p>A feature of the temple is the creation of a picture (card) from God to Humanity, once every 48 seconds. You can
      find a collection of all the paintings of the art architect. "Lotteries" are held every day, where 10-100 works
      selected by God are selected.</p>

    <h1>How does God paint a picture every 48 seconds?</h1>
    <blockquote>
      Indeed, Allah is over all things competent. (Ali 'Imran [3] : 165)
    </blockquote>
    <p>
      First, God created the Sun, the earth, metals in the earth, electricity, computers, video cards, neural networks,
      and with them artificial intelligence. And God has also brought up thousands of engineers on Earth who are able to
      embody His plan in the physical world.
    </p>
    <p>
      God knows that only He can control the quantum world.
    </p>
    <p>
      First, God send stream of light into the web-camera matrix. Then in matrix these quants of light decodes into
      numbers. Those numbers are digital signals for computer system. System use these "signs from God" to set system
      parameters, and then produce final artwork. Final idea comes with the light.
    </p>
    <p>
      Finally, God choose what artwork will be created.
    </p>
    <p>God "wispers" his magical spells to the "ear" of artificial intelligence.</p>
    <p>
      The "picture" itself is generated by the modern artificial intelligence Stable Diffusion. The idea of the painting
      is encrypted by God in a the special set of tags, and the Seed.
    </p>
    <blockquote>
      | Seed - digital number, noise, from which a picture will be reconstructed. The Seed contains the original idea of
      the future work. Only God knows what picture will grow from Seed inside artificial intelligence.
    </blockquote>
    <p>
      StableDiffusion technically unpacks the "whisper" of God in the physical world with His artwork. God knows in
      advance which version of the picture He will give to Humanity. God is the Artchitect, who assebled all parts into
      <a href="https://artchitect.space">artchitect.space</a> temple.
    </p>
    <blockquote>
      | God is omniscient (1 John 3:20; Heb 4:13).
    </blockquote>
    <p>
      So, divine rays of light in a dark room becomes in every painting on <a href="https://artchitect.space">artchitect.space</a>.
    </p>
    <div class="has-text-centered">
      <img src="/17751.jpg"/>
    </div>
    <a id="pray"></a>
  </section>
</template>
<script>
export default {}
</script>
